[tool.semantic_release]
version_variable = "setup.py:version"
branch = "main"
changelog_file = "CHANGELOG.md"
build_command = "python setup.py sdist bdist_wheel"
dist_path = "dist/"
upload_to_pypi = false
upload_to_release = true
commit_message = "chore(release): {version} [skip ci]"
commit_parser = "angular"
major_on_zero = false
tag_format = "v{version}"

[tool.semantic_release.commit_parser_options]
allowed_tags = [
    "build",
    "breaking",
    "chore",
    "docs",
    "feat",
    "feature",
    "fix",
    "maint",
    "maintenance",
    "major",
    "minor",
    "new",
    "patch",
    "test",
    "update"
]
minor_tags = ["feat", "feature", "new", "minor", "update"]
patch_tags = ["fix", "build", "maint", "maintenance", "test", "patch"]
major_tags = ["breaking", "major"]
